<?php

function cash_format($number)
{
	setlocale(LC_MONETARY, 'en_US.UTF-8');
	return money_format('%.2n', $number);
}

function escape_CSV_quotes($str)
{
	return str_replace('"','""',$str);
}

function get_rental_period($id)
{
	global $wpdb;
	$json = $wpdb->get_results($wpdb->prepare("SELECT Meta_Value FROM ".IAM_META_TABLE." WHERE Meta_Key=%s",RENTAL_PREFIX.$id));
	if (count($json)==0) {
		return 0;
	}
	return json_decode($json[0]->Meta_Value)->duration;
}

function get_email($iam_id)
{
	global $wpdb;
	$wpid = $wpdb->get_results($wpdb->prepare("SELECT WP_ID FROM ".IAM_USERS_TABLE." WHERE IAM_ID=%d",$iam_id))[0]->WP_ID;
	return get_userdata($wpid)->user_email;
}

function get_user_for_email($email)
{
	global $wpdb;
	return $wpdb->get_results("SELECT * FROM ".IAM_USERS_TABLE." WHERE WP_ID=".get_user_by('email',$email)->ID)[0];
}

function get_full_name($wpid)
{
	$u = get_userdata($wpid);
	return ucwords($u->first_name.' '.$u->last_name);
}

function include_files_in($dir)
{
	$files = glob(iam_dir(). $dir . '/*.php');
	foreach ($files as $file) {
	    require_once($file);
	}
}

function iam_make_post($url,$data,$header="Content-type: application/x-www-form-urlencoded\r\n")
{
	// use key 'http' even if you send the request to https://...
	$options = array(
	    'http' => array(
	        'header'  => $header,
	        'method'  => 'POST',
	        'content' => http_build_query($data)
	    )
	);
	$context  = stream_context_create($options);
	$result = file_get_contents($url, false, $context);
	if ($result === FALSE) { iam_throw_error('BAD_REQUEST_MADE'); }

	return $result;
}

function iam_validate_get_results($results, $location='', $fail_on_empty=false)
{
	if ($results===null) {
		iam_throw_error(DATABASE_ERROR.' '.$location);
	}
	if ($fail_on_empty && count($results)===0) {
		iam_throw_error(DATABASE_ERROR.' '.$location);
	}
}

function iam_output($val)
{
	return htmlspecialchars($val);
}

function iam_dir()
{
    $dir = plugin_dir_path( dirname( __FILE__ ) );
    $dir = strpos($dir, 'imrc-account-manager')===false ? $dir.'imrc-account-manager/' : $dir;
    return $dir;
}

function iam_url()
{
	$dir = plugin_dir_url( dirname( __FILE__ ) );
	$dir = strpos($dir, 'imrc-account-manager')===false ? $dir.'imrc-account-manager/' : $dir;
	return $dir;
}

function iam_mail($to,$subject,$message,$failure_message="Failed to send email.")
{
  if (strpos( $_SERVER['HTTP_HOST'], 'localhost' )!==false)
      return;
	try {
		if (!wp_mail($to, $subject, $message, array('Content-Type: text/html; charset=UTF-8'))) {
			throw new Exception($failure_message);
		}
	}
	catch(Exception $e) {
	   IAM::$status_message = $e->getMessage();
	}
}

function iam_respond($status='success',$content='',$message='',$redirect='')
{
	echo json_encode(['status'=>$status,'content'=>$content,'message'=>$message,'redirect'=>$redirect]);
	exit;
}

function make_nid()
{
	return md5(uniqid());
}

function ordinal_format($number) {
    $ends = array('th','st','nd','rd','th','th','th','th','th','th');
    if ((($number % 100) >= 11) && (($number%100) <= 13))
        return $number. 'th';
    else
        return $number. $ends[$number % 10];
}

function iam_validate_query($results, $location='', $fail_on_zero=false)
{
	if ($results===false) {
		iam_throw_error(DATABASE_ERROR.' '.$location);
	}
	if ($fail_on_zero && $results===0) {
		iam_throw_error(DATABASE_ERROR.' '.$location);
	}
}

function validateAndMoveImg($file)
{
	if (IAM_Sec::verifyImageFile($file['tmp_name'])) {
			$movefile = wp_handle_upload($file,array( 'test_form' => false ));
			if ( $movefile && !isset( $movefile['error'] ) ) {
					return $movefile['url'];
			} else {
					/**
					 * Error generated by _wp_handle_upload()
					 * @see _wp_handle_upload() in wp-admin/includes/file.php
					 */
					iam_throw_error( "MOVE FILE ERROR: ".$movefile['error'] );
					exit;
			}
	} else {
		iam_throw_error ( 'Error - Invalid Image File');
		exit;
	}
}

function send_to_debug_file($s)
{
    if(!file_exists(DEBUG_FILE)) {
        $debugfile = fopen(DEBUG_FILE, "w+");
        fclose($debugfile);
    }
    date_default_timezone_set(IMRC_TIME_ZONE);
    $content = "================== ".date('M-j-y g:i:s a')." =================\n".$s;
    file_put_contents(DEBUG_FILE, $content.PHP_EOL , FILE_APPEND | LOCK_EX);
}
