<?php

/**
* 
*/
class Rooms_Page extends Item_Mgmt
{
    
    public static function admin_room_callback()
    {
        $interaction = $_POST['method'];
        if (isset($_POST['name']) && isset($_POST['out-of-order']) && ($interaction=='u' && isset($_POST['x']) || $interaction=='n') ) {
            global $wpdb;
            $name = IAM_Sec::textfield_cleaner($_POST['name'], true);
            //name checks
            if (gettype($name)!='string') {
                iam_throw_error( 'Error - Invalid Input in Field: "Name"');
                exit;
            }
            if (strlen($name)>100) {
                iam_throw_error(  'Error - Field "Name" max length 100 characters');
                exit;
            }
            if (preg_match("/[;'_]/", $name)) {
                iam_throw_error('Error - Name cannot contain single quotes, semi colons, or underscores.');
            }
            if (count($wpdb->get_results($wpdb->prepare("SELECT Room_ID FROM ".IAM_ROOM_TABLE." WHERE Name=%s",$name)))>0 && $interaction=='n') {
                iam_throw_error(  'Error - A room of this name already exists');
                exit;
            }

            $out_of_order = $_POST['out-of-order'];
            if (IAM_Sec::is_num_val($out_of_order)===false) {
                iam_throw_error(  'Error - Invalid Input in Field: "Out Of Order"');
                exit;
            }

            $description = null;
            if (isset($_POST['description'])) {
                $description = IAM_Sec::textfield_cleaner($_POST['description']);
                //desc checks
                if (gettype($description)!='string') {
                    iam_throw_error(  'Error - Invalid Input in Field: "Description"');
                    exit;
                }
            }

            $pricing_description = null;
            if (isset($_POST['pricing-description'])) {
                $pricing_description = IAM_Sec::textfield_cleaner($_POST['pricing-description']);
                //desc checks
                if (gettype($description)!='string') {
                    iam_throw_error(  'Error - Invalid Input in Field: "Pricing Description"');
                    exit;
                }
            }

            $photo = null;
            if (count($_FILES)>0) {
                $file = $_FILES['photo'];
                if (IAM_Sec::verifyImageFile($file['tmp_name'],['image/jpeg','image/pjpeg','image/jpeg','image/pjpeg','image/png'])){
                    $movefile = wp_handle_upload($file,array( 'test_form' => false ));
                    if ( $movefile && !isset( $movefile['error'] ) ) {
                        $photo = $movefile['url'];
                    } else {
                        /**
                         * Error generated by _wp_handle_upload()
                         * @see _wp_handle_upload() in wp-admin/includes/file.php
                         */
                        iam_throw_error(  $movefile['error']);
                        exit;
                    }

                }
            }

            $insert_query = "";

            if ($interaction=='n') {
                //TODO: try again routine for remote case of uniqueid producing a duplicate id
                //TODO: more complex ni_id
                $ni_id = uniqid();
                if ($photo!=null) {
                    $insert_query = $wpdb->prepare("INSERT INTO ".IAM_ROOM_TABLE." (NI_ID,Name,Description,Pricing_Description,Photo,Out_Of_Order) VALUES (%s,%s,%s,%s,%s,%d)",$ni_id,$name,$description,$pricing_description,$photo,$out_of_order);
                } else {
                    $insert_query = $wpdb->prepare("INSERT INTO ".IAM_ROOM_TABLE." (NI_ID,Name,Description,Pricing_Description,Out_Of_Order) VALUES (%s,%s,%s,%s,%d)",$ni_id,$name,$description,$pricing_description,$out_of_order);
                }

            } else if ($interaction=='u') {
                $ni_id = $_POST['x'];
                if ($photo!=null) {
                    $insert_query = $wpdb->prepare("UPDATE ".IAM_ROOM_TABLE." SET Photo=%s,Name=%s,Description=%s,Pricing_Description=%s,Out_Of_Order=%d WHERE NI_ID=%s ",$photo,$name,$description,$pricing_description,$out_of_order,$ni_id);
                } else {
                    $insert_query = $wpdb->prepare("UPDATE ".IAM_ROOM_TABLE." SET Name=%s,Description=%s,Pricing_Description=%s,Out_Of_Order=%d WHERE NI_ID=%s ",$name,$description,$pricing_description,$out_of_order,$ni_id);
                }
            } else {
                iam_throw_error(INVALID_INPUT_EXCEPTION);
            }

            $result = $wpdb->query($insert_query);

            if ($result===false) {
                iam_throw_error(  "Error - An Unknown Error Occured.");
                exit;
            }

            iam_respond(SUCCESS);
        } else {
            if (!isset($_POST['name'])) {
                iam_throw_error(  'Error - Please fill out required fields: Name');
            }
            iam_throw_error(INVALID_INPUT_EXCEPTION);
        }
    }

}